# Generated by Django 3.2.9 on 2021-12-23 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nurseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lasttname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('age', models.TextField(max_length=20)),
                ('experience', models.CharField(max_length=30)),
                ('startdate', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=30)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.doctordepartment')),
                ('staffcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.staffcategory')),
            ],
        ),
    ]
