# Generated by Django 3.2.9 on 2021-12-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_doctortable'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='experience',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
