# Generated by Django 3.2.9 on 2021-12-23 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_doctortable_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctortable',
            name='image',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
