# Generated by Django 3.2.9 on 2021-12-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0005_doctortable_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordepartment',
            name='status',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
