# Generated by Django 3.2.9 on 2021-12-28 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_doctordepartment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctortable',
            old_name='fristname',
            new_name='firstname',
        ),
    ]
