# Generated by Django 3.2.9 on 2021-12-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_doctortable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='nursetable',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
