# Generated by Django 3.2.9 on 2021-12-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_nursetable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stafftable',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
