# Generated by Django 3.2.9 on 2022-01-10 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0010_stafftable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.doctordepartment')),
                ('Dr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.doctortable')),
            ],
        ),
    ]
