# Generated by Django 3.2.9 on 2022-01-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0011_doctor_time_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_time_table',
            name='date',
        ),
    ]
