# Generated by Django 3.2.9 on 2022-01-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0012_remove_doctor_time_table_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor_time_table',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
