# Generated by Django 3.2.9 on 2022-01-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0014_auto_20220112_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_time_table',
            name='end_time',
        ),
    ]
