# Generated by Django 3.2.9 on 2022-01-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0015_remove_doctor_time_table_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor_time_table',
            name='time',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
