# Generated by Django 3.2.9 on 2022-01-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_alter_doctor_time_table_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.CharField(max_length=300, null=True)),
                ('ServiceName', models.CharField(max_length=300, null=True)),
                ('ServicesDetails', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
