# Generated by Django 3.2.9 on 2021-12-22 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blogitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=400)),
                ('petname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=30)),
                ('heading', models.CharField(max_length=30)),
                ('textarea', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='fooddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=400)),
                ('protiename', models.CharField(max_length=30)),
                ('pet', models.CharField(max_length=30)),
                ('protiendetails', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='sidebolg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=200)),
                ('heading', models.CharField(max_length=20)),
                ('textarea', models.TextField()),
            ],
        ),
    ]
