# Generated by Django 3.2.9 on 2021-12-29 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_nursetable_status'),
        ('app3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancelAppoinment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=90)),
                ('pet', models.CharField(max_length=34)),
                ('petname', models.CharField(max_length=34, null=True)),
                ('petbreed', models.CharField(max_length=30)),
                ('petdisease', models.CharField(max_length=50)),
                ('petsex', models.CharField(max_length=20)),
                ('petage', models.CharField(max_length=30)),
                ('petweight', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.doctortable')),
            ],
        ),
    ]
