# Generated by Django 3.2.9 on 2022-01-05 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0002_cancelappoinment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cancelAppoinment',
        ),
    ]
