# Generated by Django 3.2.9 on 2022-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0003_delete_cancelappoinment'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooddetails',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sidebolg',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
