# Generated by Django 3.2.9 on 2022-01-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0004_auto_20220106_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitems',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
