# Generated by Django 3.2.9 on 2022-01-15 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0016_alter_doctor_time_table_time'),
        ('app3', '0005_blogitems_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('doctor', models.CharField(max_length=30)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.doctor_time_table')),
            ],
        ),
    ]
