# Generated by Django 3.2.9 on 2022-01-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app3', '0006_tokennumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokennumber',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
