# Generated by Django 3.2.9 on 2021-12-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appoinmenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=90)),
                ('doctor', models.CharField(max_length=45)),
                ('pet', models.CharField(max_length=34)),
                ('petbreed', models.CharField(max_length=30)),
                ('petdisease', models.CharField(max_length=50)),
                ('petsex', models.CharField(max_length=20)),
                ('petage', models.CharField(max_length=30)),
                ('petweight', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='feedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('phonumber', models.BigIntegerField()),
                ('message', models.TextField()),
            ],
        ),
    ]
