# Generated by Django 3.2.9 on 2021-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_appoinmenttable_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmenttable',
            name='petname',
            field=models.CharField(max_length=34, null=True),
        ),
    ]
