# Generated by Django 3.2.9 on 2021-12-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_appoinmenttable_petname'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmenttable',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
