# Generated by Django 3.2.9 on 2022-01-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_appoinmenttable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmenttable',
            name='petos_id',
            field=models.IntegerField(null=True),
        ),
    ]
