# Generated by Django 3.2.9 on 2022-01-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_appoinmenttable_petos_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appoinmenttable',
            old_name='petos_id',
            new_name='token_number',
        ),
        migrations.AddField(
            model_name='appoinmenttable',
            name='time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
