# Generated by Django 3.2.9 on 2022-01-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20220110_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appoinmenttable',
            name='token_number',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
