# Generated by Django 3.2.9 on 2022-01-17 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0017_service_table'),
        ('app1', '0016_auto_20220115_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBookinTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=40)),
                ('phonenumber', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=90)),
                ('pet', models.CharField(max_length=34)),
                ('petname', models.CharField(max_length=34, null=True)),
                ('petbreed', models.CharField(max_length=30)),
                ('petdisease', models.CharField(max_length=50)),
                ('ambulanceService', models.CharField(max_length=20)),
                ('petage', models.CharField(max_length=30)),
                ('petweight', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10, null=True)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.service_table')),
            ],
        ),
    ]
