# Generated by Django 3.2.9 on 2022-01-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_servicebookintable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebookintable',
            name='petdisease',
        ),
    ]
